RohTjWeb/Models/City.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace RohTjWeb.Models
{
    public class City: BaseModel
    {
        [Required]
        [Display(Name = "Название")]
        public string Name { get; set; }
        [Required]
        public string RegionId { get; set; }
        [Display(Name = "Область")]
        public Region Region { get; set; }
        [Display(Name ="Район")]
        public string District { get; set; }
        [Display(Name = "Сортировка")]
        public int Order { get; set; }
    }
}

RohTjWeb/Controllers/CityController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RohTjWeb.Data;
using RohTjWeb.Models;
using Microsoft.AspNetCore.Authorization;

namespace RohTjWeb.Controllers
{
    [Authorize(Roles = "Admin, Operator")]
    public class CityController : Controller
    {
        private readonly RohContext _context;

        public CityController(RohContext context)
        {
            _context = context;
        }

        // GET: City
        public async Task<IActionResult> Index()
        {
            return View(await _context.City.Include(c => c.Region).OrderByDescending(c=>c.Order).ThenBy(c=>c.Name).ToListAsync());
        }

        // GET: City/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var city = await _context.City.Include(c => c.Region).SingleOrDefaultAsync(m => m.Id == id);
            if (city == null)
            {
                return NotFound();
            }

            return View(city);
        }

        // GET: City/Create
        public IActionResult Create()
        {
            PopulateRegionsDropDownList();

            return View();
        }

        // POST: City/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,RegionId,District,Order,CreatedAt,Name,UpdatedAt")] City city)
        {
            city.Id = Guid.NewGuid().ToString();
            if (ModelState.IsValid)
            {
                _context.Add(city);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            PopulateRegionsDropDownList(city.RegionId);

            return View(city);
        }

        // GET: City/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var city = await _context.City.Include(c => c.Region).SingleOrDefaultAsync(m => m.Id == id);
            if (city == null)
            {
                return NotFound();
            }
            PopulateRegionsDropDownList(city.RegionId);

            return View(city);
        }

        // POST: City/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Id,RegionId, Order, District,CreatedAt,Name,UpdatedAt")] City city)
        {
            if (id != city.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(city);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CityExists(city.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            PopulateRegionsDropDownList(city.RegionId);
            return View(city);
        }

        // GET: City/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var city = await _context.City.SingleOrDefaultAsync(m => m.Id == id);
            if (city == null)
            {
                return NotFound();
            }

            return View(city);
        }

        // POST: City/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var city = await _context.City.SingleOrDefaultAsync(m => m.Id == id);
            _context.City.Remove(city);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        private void PopulateRegionsDropDownList(string selectedRegin = null)
        {
            var regionsQuery = from d in _context.Region
                               orderby d.Name
                               select d;
            ViewBag.RegionID = new SelectList(regionsQuery.AsNoTracking(), "Id", "Name", selectedRegin);
        }
        private bool CityExists(string id)
        {
            return _context.City.Any(e => e.Id == id);
        }
    }
}

RohTjWeb/Views/City/Create.cshtml
@model RohTjWeb.Models.City

@{
    ViewData["Title"] = "Создать";
}

<h2>Создать</h2>

<form asp-action="Create">
    <div class="form-horizontal">
        <h4>Город</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="Name" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Region" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <select asp-for="RegionId" class="form-control" asp-items="ViewBag.RegionID">
                    <option value="">-- Select region --</option>
                </select>
                <span asp-validation-for="RegionId" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="District" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="District" class="form-control" />
                <span asp-validation-for="District" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Order" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Order" class="form-control" />
                <span asp-validation-for="Order" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Создать" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Назад</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

RohTjWeb/Views/City/Delete.cshtml
@model RohTjWeb.Models.City

@{
    ViewData["Title"] = "Удаление";
}

<h2>Удаление</h2>

<h3>Вы уверены, что хотите удалить?</h3>
<div>
    <h4>Город</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <div class="form-actions no-color">
            <input type="submit" value="Удалить" class="btn btn-default" /> |
            <a asp-action="Index">Назад</a>
        </div>
    </form>
</div>

RohTjWeb/Views/City/Details.cshtml
@model RohTjWeb.Models.City

@{
    ViewData["Title"] = "Детали";
}

<h2>Детали</h2>

<div>
    <h4>Город</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Region.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Region.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.District)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.District)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Order)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Order)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Назад</a>
</div>

RohTjWeb/Views/City/Edit.cshtml
@model RohTjWeb.Models.City

@{
    ViewData["Title"] = "Редактировать";
}

<h2>Редактировать</h2>

<form asp-action="Edit">
    <div class="form-horizontal">
        <h4>Город</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input type="hidden" asp-for="Id" />
        <div class="form-group">
            <label asp-for="Name" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Region" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <select asp-for="RegionId" class="form-control" asp-items="ViewBag.RegionID">
                    <option value="">-- Выберите Область --</option>
                </select>
                <span asp-validation-for="RegionId" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="District" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="District" class="form-control" />
                <span asp-validation-for="District" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Order" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Order" class="form-control" />
                <span asp-validation-for="Order" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Сохранить" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Назад</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

RohTjWeb/Views/City/Index.cshtml
@using NonFactors.Mvc.Grid;

@model IEnumerable<RohTjWeb.Models.City>

@{
    ViewData["Title"] = "Index";
}

<h2>Город</h2>

<p>
    <a asp-action="Create">Создать новый</a>
</p>

@(Html
    .Grid(Model)
    .Build(columns =>
    {
        columns.Add(model => model.Name).Titled("Название");
        columns.Add(model => model.Region.Name).Titled("Область");
        columns.Add(model => model.District).Titled("Район");
        columns.Add(model => model.Order).Titled("Сартировка");
        columns.Add(model => $"<div class='dropdown'>" +
        $"<button class='btn btn-sm btn-primary dropdown-toggle' type='button' data-toggle='dropdown'>Действие <span class='caret'></span></button>" +
        $"<ul class='dropdown-menu'>" +
        $"<li><a href=\"{Url.Action("Edit", "City")}/{model.Id}\">Редактировать</a></li>" +
        $"<li><a href=\"{Url.Action("Details", "City")}/{model.Id}\">Детали</a></li>" +
        $"<li><a href=\"{Url.Action("Delete", "City")}/{model.Id}\">Удаление</a></li>" +
        $"</ul></div>").Encoded(false);
        
    })
    .Filterable()
    .Sortable()
    .Pageable()
    .Empty("По вашему запросу ничего не найдено")
)