RohTjWeb/Models/GeoLocation.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;


namespace RohTjWeb.Models
{
    public class GeoLocation: BaseModel
    {
        [Display(Name = "Широта")]
        public double Latitude { get; set; }
        [Display(Name = "Долгота")]
        public double Longitude { get; set; }
        public Client Client { get; set; }
        public string ClientId { get; set; }
        public bool IsDriver { get; set; }
    }
}

RohTjWeb/Controllers/GeoLocationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RohTjWeb.Data;
using RohTjWeb.Models;
using Microsoft.AspNetCore.Authorization;

namespace RohTjWeb.Controllers
{
    [Authorize(Roles = "Admin, Operator, Manager")]
    public class GeoLocationController : Controller
    {
        private readonly RohContext _context;

        public GeoLocationController(RohContext context)
        {
            _context = context;    
        }

        // GET: GeoLocation
        public async Task<IActionResult> Index()
        {
            var rohContext = _context.GeoLocation.Include(g => g.Client);
            return View(await rohContext.ToListAsync());
        }

        // GET: GeoLocation/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var geoLocation = await _context.GeoLocation.SingleOrDefaultAsync(m => m.Id == id);
            if (geoLocation == null)
            {
                return NotFound();
            }

            return View(geoLocation);
        }

        // GET: GeoLocation/Create
        public IActionResult Create()
        {
            ViewData["ClientId"] = new SelectList(_context.Client, "Id", "Id");
            return View();
        }

        // POST: GeoLocation/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,ClientId,CreatedAt,IsDriver,Latitude,Longitude,UpdatedAt")] GeoLocation geoLocation)
        {
            if (ModelState.IsValid)
            {
                _context.Add(geoLocation);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewData["ClientId"] = new SelectList(_context.Client, "Id", "Id", geoLocation.ClientId);
            return View(geoLocation);
        }

        // GET: GeoLocation/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var geoLocation = await _context.GeoLocation.Include(c=>c.Client).SingleOrDefaultAsync(m => m.Id == id);
            if (geoLocation == null)
            {
                return NotFound();
            }
            var clientsQuery = from d in _context.Client
                               orderby d.PhoneNumber
                               select d;
            ViewData["ClientId"] = new SelectList(clientsQuery, "Id", "PhoneNumber", geoLocation.ClientId);
            return View(geoLocation);
        }

        // POST: GeoLocation/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Id,ClientId,CreatedAt,IsDriver,Latitude,Longitude,UpdatedAt")] GeoLocation geoLocation)
        {
            if (id != geoLocation.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(geoLocation);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GeoLocationExists(geoLocation.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            ViewData["ClientId"] = new SelectList(_context.Client, "Id", "Id", geoLocation.ClientId);
            return View(geoLocation);
        }

        // GET: GeoLocation/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var geoLocation = await _context.GeoLocation.SingleOrDefaultAsync(m => m.Id == id);
            if (geoLocation == null)
            {
                return NotFound();
            }

            return View(geoLocation);
        }

        // POST: GeoLocation/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var geoLocation = await _context.GeoLocation.SingleOrDefaultAsync(m => m.Id == id);
            _context.GeoLocation.Remove(geoLocation);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool GeoLocationExists(string id)
        {
            return _context.GeoLocation.Any(e => e.Id == id);
        }
    }
}

RohTjWeb/Views/GeoLocation/Create.cshtml
@model RohTjWeb.Models.GeoLocation

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<form asp-action="Create">
    <div class="form-horizontal">
        <h4>GeoLocation</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="ClientId" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <select asp-for="ClientId" class ="form-control" asp-items="ViewBag.ClientId"></select>
            </div>
        </div>
        
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <div class="checkbox">
                    <input asp-for="IsDriver" />
                    <label asp-for="IsDriver"></label>
                </div>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Latitude" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Latitude" class="form-control" />
                <span asp-validation-for="Latitude" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Longitude" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Longitude" class="form-control" />
                <span asp-validation-for="Longitude" class="text-danger" />
            </div>
        </div>
        
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

RohTjWeb/Views/GeoLocation/Delete.cshtml
@model RohTjWeb.Models.GeoLocation

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>GeoLocation</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CreatedAt)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CreatedAt)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IsDriver)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IsDriver)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Latitude)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Latitude)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Longitude)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Longitude)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.UpdatedAt)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.UpdatedAt)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            <a asp-action="Index">Back to List</a>
        </div>
    </form>
</div>

RohTjWeb/Views/GeoLocation/Details.cshtml
@model RohTjWeb.Models.GeoLocation

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>GeoLocation</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CreatedAt)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CreatedAt)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IsDriver)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IsDriver)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Latitude)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Latitude)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Longitude)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Longitude)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.UpdatedAt)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.UpdatedAt)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

RohTjWeb/Views/GeoLocation/Edit.cshtml
@model RohTjWeb.Models.GeoLocation

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<form asp-action="Edit">
    <div class="form-horizontal">
        <h4>GeoLocation</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="Id" />
        <div class="form-group">
            <label asp-for="ClientId" class="control-label col-md-2"></label>
            <div class="col-md-10">
                <select asp-for="ClientId" class="form-control" asp-items="ViewBag.ClientId"></select>
                <span asp-validation-for="ClientId" class="text-danger" />
            </div>
        </div>
        
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <div class="checkbox">
                    <input asp-for="IsDriver" />
                    <label asp-for="IsDriver"></label>
                </div>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Latitude" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Latitude" class="form-control" />
                <span asp-validation-for="Latitude" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Longitude" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Longitude" class="form-control" />
                <span asp-validation-for="Longitude" class="text-danger" />
            </div>
        </div>
        
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

RohTjWeb/Views/GeoLocation/Index.cshtml
@using NonFactors.Mvc.Grid;

@model IEnumerable<RohTjWeb.Models.GeoLocation>

@{
    ViewData["Title"] = "Местоположения";
}

<h2>Местоположения</h2>

<p>
    <a asp-action="Create">Создать новый</a>
</p>

@(Html
    .Grid(Model)
    .Build(columns =>
    {
        columns.Add(model => model.CreatedAt).Titled("Дата создания");
        columns.Add(model => model.IsDriver).Titled("Водитель");
        columns.Add(model => model.Client.PhoneNumber).Titled("Телефон");
        //columns.Add(model => model.ClientId).Titled("ID");
        columns.Add(model => model.Latitude).Titled("Широта");
        columns.Add(model => model.Longitude).Titled("Долгота");
        columns.Add(model => model.UpdatedAt).Titled("Дата обновления");
        columns.Add(model => $"<div class='dropdown'>" +
        $"<button class='btn btn-sm btn-primary dropdown-toggle' type='button' data-toggle='dropdown'>Действие <span class='caret'></span></button>" +
        $"<ul class='dropdown-menu'>" +
        $"<li><a href=\"{Url.Action("Edit", "GeoLocation")}/{model.Id}\">Редактировать</a></li>" +
        $"<li><a href=\"{Url.Action("Details", "GeoLocation")}/{model.Id}\">Детали</a></li>" +
        $"<li><a href=\"{Url.Action("Delete", "GeoLocation")}/{model.Id}\">Удаление</a></li>" +
        $"</ul></div>").Encoded(false);
        
    })
    .Filterable()
    .Sortable()
    .Pageable()
    .Empty("По вашему запросу ничего не найдено")
)