RohTjWeb/Models/Region.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace RohTjWeb.Models
{
    public class Region: BaseModel
    {
        [Display(Name = "Область")]
        public string Name { get; set; }
    }
}

RohTjWeb/Controllers/RegionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RohTjWeb.Data;
using RohTjWeb.Models;
using Microsoft.AspNetCore.Authorization;

namespace RohTjWeb.Controllers
{
    [Authorize]
    public class RegionController : Controller
    {
        private readonly RohContext _context;

        public RegionController(RohContext context)
        {
            _context = context;    
        }

        // GET: Region
        public async Task<IActionResult> Index()
        {
            return View(await _context.Region.ToListAsync());
        }
        
        // GET: Region/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var region = await _context.Region.SingleOrDefaultAsync(m => m.Id == id);
            if (region == null)
            {
                return NotFound();
            }

            return View(region);
        }

        // GET: Region/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Region/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,CreatedAt,Name,UpdatedAt")] Region region)
        {
            region.Id = Guid.NewGuid().ToString();
            if (ModelState.IsValid)
            {
                _context.Add(region);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(region);
        }

        // GET: Region/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var region = await _context.Region.SingleOrDefaultAsync(m => m.Id == id);
            if (region == null)
            {
                return NotFound();
            }
            return View(region);
        }

        // POST: Region/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Id,CreatedAt,Name,UpdatedAt")] Region region)
        {
            if (id != region.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(region);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RegionExists(region.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            return View(region);
        }

        // GET: Region/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var region = await _context.Region.SingleOrDefaultAsync(m => m.Id == id);
            if (region == null)
            {
                return NotFound();
            }

            return View(region);
        }

        // POST: Region/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var region = await _context.Region.SingleOrDefaultAsync(m => m.Id == id);
            _context.Region.Remove(region);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool RegionExists(string id)
        {
            return _context.Region.Any(e => e.Id == id);
        }
    }
}

RohTjWeb/Views/Region/Create.cshtml
@model RohTjWeb.Models.Region

@{
    ViewData["Title"] = "Создать";
}

<h2>Создать</h2>

<form asp-action="Create">
    <div class="form-horizontal">
        <h4>Область</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="Name" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Создать" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Назад</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

RohTjWeb/Views/Region/Delete.cshtml
@model RohTjWeb.Models.Region

@{
    ViewData["Title"] = "Удаление";
}

<h2>Удаление</h2>

<h3>Вы уверены, что хотите удалить?</h3>
<div>
    <h4>Область</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <div class="form-actions no-color">
            <input type="submit" value="Удалить" class="btn btn-default" /> |
            <a asp-action="Index">Назад</a>
        </div>
    </form>
</div>

RohTjWeb/Views/Region/Details.cshtml
@model RohTjWeb.Models.Region

@{
    ViewData["Title"] = "Детали";
}

<h2>Детали</h2>

<div>
    <h4>Область</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Редактировать</a> |
    <a asp-action="Index">Назад</a>
</div>

RohTjWeb/Views/Region/Edit.cshtml
@model RohTjWeb.Models.Region

@{
    ViewData["Title"] = "Редактировать";
}

<h2>Редактировать</h2>

<form asp-action="Edit">
    <div class="form-horizontal">
        <h4>Область</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="Id" />
        <div class="form-group">
            <label asp-for="Name" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Сохранить" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Назад</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

RohTjWeb/Views/Region/Index.cshtml
@using NonFactors.Mvc.Grid;

@model IEnumerable<RohTjWeb.Models.Region>

@{
    ViewData["Title"] = "Область";
}

<h2>Область</h2>

<p>
    <a asp-action="Create">Создать новую область</a>
</p>

@(Html
    .Grid(Model)
    .Build(columns =>
    {
        columns.Add(model => model.Name).Titled("Область");
        columns.Add(model => $"<div class='dropdown'>" +
        $"<button class='btn btn-sm btn-primary dropdown-toggle' type='button' data-toggle='dropdown'>Действие <span class='caret'></span></button>" +
        $"<ul class='dropdown-menu'>" +
        $"<li><a href=\"{Url.Action("Edit", "Region")}/{model.Id}\">Редактировать</a></li>" +
        $"<li><a href=\"{Url.Action("Details", "Region")}/{model.Id}\">Детали</a></li>" +
        $"<li><a href=\"{Url.Action("Delete", "Region")}/{model.Id}\">Удаление</a></li>" +
        $"</ul></div>").Encoded(false);
        
    })
    .Filterable()
    .Sortable()
    .Pageable()
    .Empty("По вашему запросу ничего не найдено")
)